In [1]:
import numpy as np

In [28]:
targets = np.load("./Lab4_data_targets_orig.npz")['arr_0']

std_dev = 0.8
rand_arr = np.random.normal(loc=0, scale=std_dev, size=targets.shape)

arr = targets.copy()
arr += rand_arr
arr = np.round(arr * 2) / 2
arr = np.clip(arr, a_min=0.5, a_max=5)

In [29]:
arr

array([2.5, 4. , 4.5, ..., 4.5, 4. , 5. ])

In [30]:
targets

array([4. , 3.5, 4. , ..., 5. , 5. , 5. ])

In [31]:
new = arr != targets
new

array([ True,  True,  True, ...,  True,  True, False])

In [32]:
np.sum(new)

35879

In [34]:
np.savez("./Lab4_data_targets.npz", targets = arr)

Movies

In [27]:
movies = np.load("./Lab4_data_items_orig.npz")['arr_0']
features = np.load("./Lab4_data_items_orig.npz")['arr_1']

movies.shape

(50884, 17)

In [28]:
np.set_printoptions(precision=2, suppress=True)
print(movies)


[[  6874.     2003.        3.96 ...      0.        0.        1.  ]
 [  8798.     2004.        3.76 ...      0.        0.        1.  ]
 [ 46970.     2006.        3.25 ...      0.        0.        0.  ]
 ...
 [168250.     2017.        3.63 ...      0.        0.        0.  ]
 [168250.     2017.        3.63 ...      0.        0.        0.  ]
 [168252.     2017.        4.28 ...      0.        1.        0.  ]]


In [29]:
movies_reshuffle = np.random.permutation(movies)
movies_reshuffle = movies_reshuffle[:,3:] # remove id, year, and avg rting

In [30]:
movies_reshuffle.shape

(50884, 14)

In [31]:
#std_dev = 0.3
#rand_arr = np.random.normal(loc=0, scale=std_dev, size=movies_reshuffle.shape[0])


In [32]:
#rand_arr = rand_arr.round()
#movies_reshuffle[:,0] += rand_arr # rand year
#movies_reshuffle[:,1] = np.round(movies_reshuffle[:,1], 2) # round rating

In [33]:
(movies_reshuffle)

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.]])

In [34]:
features = np.array(['Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Horror', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller'])

In [35]:
np.savez("./Lab4_data_items.npz", items = movies_reshuffle, features = features)

users

In [170]:
users = np.load("./Lab4_data_users_orig.npz")['arr_0']
features = np.load("./Lab4_data_users_orig.npz")['arr_1']

users.shape

(50884, 17)

In [171]:
users_uniq = np.unique(users,axis=0)
users_uniq = users_uniq[:,3:]

In [176]:
users_uniq.shape

(397, 14)

In [177]:
std_dev = 0.4
users_rting_rnd = np.random.normal(loc=0, scale=std_dev, size = users_uniq.shape)
users_uniq[users_uniq>1.5] += users_rting_rnd[users_uniq>1.5]

In [178]:
users_reshuffle = np.random.permutation(users_uniq)
users_round = np.round(users_reshuffle, 2)

boost the qty of rows

In [181]:
rows_qty = 50884

num_tiles = int(np.ceil(rows_qty / users_round.shape[0]))
tiled_arr = np.tile(users_round, (num_tiles, 1))
result = tiled_arr[:rows_qty, :]

array([[4.15, 4.74, 0.  , ..., 0.  , 5.56, 4.93],
       [5.11, 0.  , 5.45, ..., 0.  , 0.  , 0.  ],
       [4.66, 3.86, 5.17, ..., 4.24, 4.3 , 4.23],
       ...,
       [2.26, 3.4 , 2.42, ..., 1.83, 2.79, 1.9 ],
       [2.9 , 3.18, 3.89, ..., 2.77, 2.62, 3.42],
       [4.7 , 3.23, 1.  , ..., 2.33, 4.78, 4.48]])

In [148]:
features = np.array(['Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Horror', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller'])

In [182]:
np.savez("./Lab4_data_users.npz", users = result, features = features)