# Given

Datasets from Lab3 (house prices) and Lab5 (custom made)

# Find

Regression models using scikit (aka sklearn)

# Solution

In [12]:
import numpy as np
from sklearn.linear_model import LinearRegression, LogisticRegression

### Regression

In [13]:
data = np.loadtxt("./houses.txt", delimiter=",")

x = data[:,0:4]
y = data[:,4]

#### SKLearn approach

##### weights

In [14]:
LinModel = LinearRegression()
LinRegression = LinModel.fit(x,y)
LinRegression.coef_

array([  0.26836643, -32.90362407, -67.28804158,  -1.46516763])

##### prediction for cost of 1200 sqft, 3 bedrooms, 1 floor, 40 years old

In [15]:
predict = np.array([1200, 3, 1, 40]).reshape(1, -1)
LinRegression.predict(predict)

array([318.93635904])

##### Accuracy

In [16]:
LinRegression.score(x, y)

0.959428104927808

### Classification

In [17]:
x = np.array([[0.5, 1.5], [1, 1], [1.5, 0.5], [3, 0.5], [2, 2], [1, 2.5]])
y = np.array([0, 0, 0, 1, 1, 1])

#### SKLearn approach

##### weights

In [18]:
LogModel = LogisticRegression()
LogRegression = LogModel.fit(x,y)
# Return the mean accuracy on the given test data and labels.
LogRegression.coef_

array([[0.90411349, 0.73587543]])

##### Accuracy

In [20]:
LogRegression.score(x, y)

1.0